import Link from 'next/link';
import { ArrowDown, ArrowLeft, ArrowUp, CheckCircle2, Copy, Plus, Sparkles, Trash2 } from 'lucide-react';
import { notFound } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { addPage, deletePage, duplicatePage, generateBookPlan, movePage, savePagePlan, togglePageApproval } from './actions';

export default async function BookPlanPage({ params }: { params: Promise<{ bookId: string }> }) {
 const {bookId}=await params; const supabase=await createClient(); const {data:book}=await supabase.from('books').select('id,title,page_count').eq('id',bookId).single(); if(!book) notFound();
 const {data:pages,error}=await supabase.from('book_pages').select('id,page_number,title,concept,description,notes,status,approved').eq('book_id',bookId).order('page_number'); if(error) throw new Error(`BOOK_PLAN_LOAD_FAILED: ${error.message}`); const approvedCount=pages?.filter(p=>p.approved).length??0; const total=pages?.length??0;
 return <><section className="hero-row compact"><div><span className="section-kicker">CREATION ENGINE · BOOK PLANNER</span><h1>{book.title} — Book Plan</h1><p>Generate draft concepts, organize pages, and approve each page before Prompt Studio.</p></div><Link className="outline-btn" href="/books"><ArrowLeft size={16}/> My Books</Link></section>
 <section className="card" style={{padding:'24px',marginBottom:'20px'}}><div className="wizard-title"><Sparkles/><div><h2>{approvedCount} of {total} pages approved</h2><p>AI regeneration updates draft pages only. Approved pages are preserved unless you return them to Draft first.</p></div></div><div className="progress"><span style={{width:`${total?Math.round((approvedCount/total)*100):0}%`}}/></div><form action={generateBookPlan} className="form-grid top-space"><input type="hidden" name="book_id" value={bookId}/><label>Desired feel<input name="feel" placeholder="Calm, playful, magical, educational..."/></label><label>Must appear<input name="must_appear" placeholder="Recurring subjects or themes"/></label><label className="full">Avoid<input name="avoid" placeholder="Anything the plan should avoid"/></label><div className="full wizard-actions"><button className="primary-btn" type="submit" disabled={total>0&&approvedCount===total}><Sparkles size={16}/> {approvedCount?'Regenerate Draft Pages':'Generate Draft Book Plan'}</button></div></form></section>
 <section className="card" style={{padding:'18px',marginBottom:'20px'}}><form action={addPage}><input type="hidden" name="book_id" value={bookId}/><button className="outline-btn"><Plus size={16}/> Add Page</button></form></section>
 <section style={{display:'grid',gap:'16px'}}>{pages?.map((page,index)=><article className="card" style={{padding:'22px'}} key={page.id}><div className="label-row"><span className={page.approved?'status ready':'status planning'}>PAGE {page.page_number}</span>{page.approved&&<span><CheckCircle2 size={16}/> Approved</span>}</div><form action={savePagePlan}><input type="hidden" name="book_id" value={bookId}/><input type="hidden" name="page_id" value={page.id}/><div className="form-grid top-space"><label>Page title<input name="title" defaultValue={page.title??''}/></label><label>Concept<input name="concept" defaultValue={page.concept??''}/></label><label className="full">Description<textarea name="description" defaultValue={page.description??''}/></label><label className="full">Notes<textarea name="notes" defaultValue={page.notes??''}/></label></div><div className="wizard-actions"><button className="outline-btn">Save Page</button></div></form><div className="wizard-actions"><form action={togglePageApproval}><input type="hidden" name="book_id" value={bookId}/><input type="hidden" name="page_id" value={page.id}/><input type="hidden" name="approved" value={String(page.approved)}/><button className="primary-btn">{page.approved?'Return to Draft':'Approve Page'}</button></form><form action={movePage}><input type="hidden" name="book_id" value={bookId}/><input type="hidden" name="page_id" value={page.id}/><input type="hidden" name="direction" value="up"/><button className="outline-btn" disabled={index===0} title="Move page up"><ArrowUp size={16}/></button></form><form action={movePage}><input type="hidden" name="book_id" value={bookId}/><input type="hidden" name="page_id" value={page.id}/><input type="hidden" name="direction" value="down"/><button className="outline-btn" disabled={index===total-1} title="Move page down"><ArrowDown size={16}/></button></form><form action={duplicatePage}><input type="hidden" name="book_id" value={bookId}/><input type="hidden" name="page_id" value={page.id}/><button className="outline-btn"><Copy size={16}/> Duplicate</button></form><form action={deletePage}><input type="hidden" name="book_id" value={bookId}/><input type="hidden" name="page_id" value={page.id}/><button className="outline-btn"><Trash2 size={16}/> Delete</button></form></div></article>)}</section><div className="wizard-actions"><Link className="primary-btn" href={`/books/${bookId}/style`}>Continue to Style Lock</Link></div></>;
}
