'use client';
import { useState } from 'react';
import { ArrowLeft, ArrowRight, BookHeart, Check, Sparkles } from 'lucide-react';
import { createBook } from './actions';

const audiences=['Toddler','Kids 4–7','Kids 8–12','Teen','Adult Relaxation','Adult Intricate','Educational','Affirmations','Custom'];
const styles=['Cute','Cartoon','Simple','Botanical','Intricate','Cozy','Geometric','Fantasy','Custom'];

export default function NewBookPage(){
 const [step,setStep]=useState(1); const [audience,setAudience]=useState('Adult Relaxation'); const [style,setStyle]=useState('Cozy'); const [title,setTitle]=useState(''); const [subtitle,setSubtitle]=useState(''); const [theme,setTheme]=useState(''); const [description,setDescription]=useState(''); const [ageRange,setAgeRange]=useState(''); const [pages,setPages]=useState(30); const [lineWeight,setLineWeight]=useState('Medium'); const [background,setBackground]=useState('Balanced'); const [coloringSpace,setColoringSpace]=useState('Balanced'); const [orientation,setOrientation]=useState('Portrait'); const [bleed,setBleed]=useState('No bleed'); const [printing,setPrinting]=useState('Single-sided');
 return <form action={createBook} className="wizard-shell"><input type="hidden" name="audience" value={audience}/><input type="hidden" name="illustration_style" value={style}/><input type="hidden" name="line_weight" value={lineWeight}/><input type="hidden" name="background_detail" value={background}/><input type="hidden" name="coloring_space" value={coloringSpace}/><input type="hidden" name="orientation" value={orientation}/><input type="hidden" name="bleed" value={bleed}/><input type="hidden" name="page_printing" value={printing}/><input type="hidden" name="trim_width" value="8.5"/><input type="hidden" name="trim_height" value="11"/>
 <div className="wizard-head"><span className="section-kicker">NEW BOOK WIZARD</span><h1>Create your next coloring book</h1><p>We’ll guide you through the creative decisions and save the finished setup to your studio.</p><div className="stepper">{[1,2,3,4,5].map(n=><div key={n} className={n<=step?'step active':'step'}><span>{n<step?<Check size={15}/>:n}</span><small>{['Audience','Details','Art Style','Format','Review'][n-1]}</small></div>)}</div></div><div className="wizard-card card">
 {step===1&&<><div className="wizard-title"><BookHeart/><div><h2>Who is this book for?</h2><p>Choose the audience that best matches your idea.</p></div></div><div className="option-grid">{audiences.map(a=><button type="button" key={a} onClick={()=>setAudience(a)} className={audience===a?'option-card selected':'option-card'}><strong>{a}</strong><span>{a.includes('Adult')?'Relaxing and creative experiences':a.includes('Kids')?'Age-appropriate coloring fun':a==='Affirmations'?'Positive words and mindful coloring':'A flexible creative starting point'}</span>{audience===a&&<Check size={18}/>}</button>)}</div></>}
 {step===2&&<><div className="wizard-title"><Sparkles/><div><h2>Tell us about your book</h2><p>Give the project a working identity.</p></div></div><div className="form-grid"><label>Book title<input name="title" required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Your book title"/></label><label>Subtitle<input name="subtitle" value={subtitle} onChange={e=>setSubtitle(e.target.value)} placeholder="Optional subtitle"/></label><label className="full">Theme<input name="theme" value={theme} onChange={e=>setTheme(e.target.value)} placeholder="Describe the theme"/></label><label>Number of coloring pages<input name="page_count" type="number" min="1" max="100" value={pages} onChange={e=>setPages(Number(e.target.value))}/></label><label>Age range<input name="age_range" value={ageRange} onChange={e=>setAgeRange(e.target.value)} placeholder="Optional"/></label><label className="full">Description<textarea name="description" value={description} onChange={e=>setDescription(e.target.value)} placeholder="What should someone feel or experience while coloring this book?"/></label></div></>}
 {step===3&&<><div className="wizard-title"><Sparkles/><div><h2>Choose your visual direction</h2><p>This becomes the starting point for your Style Lock.</p></div></div><div className="style-grid">{styles.map(s=><button type="button" key={s} onClick={()=>setStyle(s)} className={style===s?'style-choice selected':'style-choice'}><div className="style-swatch">{s==='Cozy'?'⌂':s==='Botanical'?'❀':s==='Fantasy'?'✦':'✎'}</div><strong>{s}</strong></button>)}</div><div className="form-grid top-space"><label>Line weight<select value={lineWeight} onChange={e=>setLineWeight(e.target.value)}><option>Thin</option><option>Medium</option><option>Thick</option></select></label><label>Background detail<select value={background} onChange={e=>setBackground(e.target.value)}><option>Minimal</option><option>Balanced</option><option>Detailed</option></select></label><label>Coloring space<select value={coloringSpace} onChange={e=>setColoringSpace(e.target.value)}><option>Large</option><option>Balanced</option><option>Small / Intricate</option></select></label></div><div className="style-summary"><strong>Live Style Summary</strong><p>{style} illustrations · {lineWeight.toLowerCase()} line weight · {background.toLowerCase()} backgrounds · designed for {audience}.</p></div></>}
 {step===4&&<><div className="wizard-title"><BookHeart/><div><h2>Set up your book format</h2><p>The MVP begins with the approved 8.5 × 11 format; additional templates remain available later in the workflow.</p></div></div><div className="format-grid"><button type="button" className="format-card selected"><span className="paper portrait"></span><strong>8.5 × 11 in</strong><small>Selected print format</small></button></div><div className="form-grid top-space"><label>Orientation<select value={orientation} onChange={e=>setOrientation(e.target.value)}><option>Portrait</option><option>Landscape</option></select></label><label>Bleed<select value={bleed} onChange={e=>setBleed(e.target.value)}><option>No bleed</option><option>Bleed</option></select></label><label>Page printing<select value={printing} onChange={e=>setPrinting(e.target.value)}><option>Single-sided</option><option>Double-sided</option></select></label></div></>}
 {step===5&&<><div className="wizard-title"><Check/><div><h2>Review your new book</h2><p>Creating it now writes the project, settings, style profile, and {pages} page records to Supabase.</p></div></div><div className="review-panel"><div><small>TITLE</small><strong>{title||'Title required'}</strong></div><div><small>AUDIENCE</small><strong>{audience}</strong></div><div><small>PAGES</small><strong>{pages} coloring pages</strong></div><div><small>STYLE</small><strong>{style}</strong></div><div><small>FORMAT</small><strong>8.5 × 11 in · {orientation}</strong></div><div><small>THEME</small><strong>{theme||'Not specified yet'}</strong></div></div><div className="ready-banner"><Sparkles/><div><strong>Your studio is ready.</strong><p>After creation you’ll continue directly into the real Book Planner.</p></div></div></>}
 <div className="wizard-actions"><button type="button" className="ghost-btn" disabled={step===1} onClick={()=>setStep(Math.max(1,step-1))}><ArrowLeft size={17}/> Back</button>{step<5?<button type="button" className="primary-btn" onClick={()=>setStep(step+1)} disabled={step===2&&!title.trim()}>Continue <ArrowRight size={17}/></button>:<button type="submit" className="primary-btn" disabled={!title.trim()}>Create My Book <Sparkles size={17}/></button>}</div></div></form>
}
