'use client';
import { useState } from 'react';
import { ArrowLeft, ArrowRight, BookHeart, Check, Sparkles } from 'lucide-react';

const audiences=['Toddler','Kids 4–7','Kids 8–12','Teen','Adult Relaxation','Adult Intricate','Educational','Affirmations','Custom'];
const styles=['Cute','Cartoon','Simple','Botanical','Intricate','Cozy','Geometric','Fantasy','Custom'];

export default function NewBookPage(){
 const [step,setStep]=useState(1); const [audience,setAudience]=useState('Adult Relaxation'); const [style,setStyle]=useState('Cozy'); const [title,setTitle]=useState(''); const [theme,setTheme]=useState(''); const [pages,setPages]=useState(30);
 return <div className="wizard-shell"><div className="wizard-head"><span className="section-kicker">NEW BOOK WIZARD</span><h1>Create your next coloring book</h1><p>We’ll guide you through the creative decisions. You can change them later.</p><div className="stepper">{[1,2,3,4,5].map(n=><div key={n} className={n<=step?'step active':'step'}><span>{n<step?<Check size={15}/>:n}</span><small>{['Audience','Details','Art Style','Format','Review'][n-1]}</small></div>)}</div></div><div className="wizard-card card">
 {step===1&&<><div className="wizard-title"><BookHeart/><div><h2>Who is this book for?</h2><p>Choose the audience that best matches your idea.</p></div></div><div className="option-grid">{audiences.map(a=><button key={a} onClick={()=>setAudience(a)} className={audience===a?'option-card selected':'option-card'}><strong>{a}</strong><span>{a.includes('Adult')?'Relaxing and creative experiences':a.includes('Kids')?'Age-appropriate coloring fun':a==='Affirmations'?'Positive words and mindful coloring':'A flexible creative starting point'}</span>{audience===a&&<Check size={18}/>}</button>)}</div></>}
 {step===2&&<><div className="wizard-title"><Sparkles/><div><h2>Tell us about your book</h2><p>Give the project a working identity. Nothing has to be perfect yet.</p></div></div><div className="form-grid"><label>Book title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Quiet Moments"/></label><label>Subtitle<input placeholder="e.g. 30 Cozy Spaces to Color"/></label><label className="full">Theme<input value={theme} onChange={e=>setTheme(e.target.value)} placeholder="Cozy rooms, reading corners, warm cafés..."/></label><label>Number of coloring pages<input type="number" min="1" max="100" value={pages} onChange={e=>setPages(Number(e.target.value))}/></label><label>Age range<input placeholder="Optional"/></label><label className="full">Description<textarea placeholder="What should someone feel or experience while coloring this book?"/></label></div></>}
 {step===3&&<><div className="wizard-title"><Sparkles/><div><h2>Choose your visual direction</h2><p>This becomes the starting point for your Style Lock.</p></div></div><div className="style-grid">{styles.map(s=><button key={s} onClick={()=>setStyle(s)} className={style===s?'style-choice selected':'style-choice'}><div className="style-swatch">{s==='Cozy'?'⌂':s==='Botanical'?'❀':s==='Fantasy'?'✦':'✎'}</div><strong>{s}</strong></button>)}</div><div className="form-grid top-space"><label>Line weight<select defaultValue="Medium"><option>Thin</option><option>Medium</option><option>Thick</option></select></label><label>Background detail<select defaultValue="Balanced"><option>Minimal</option><option>Balanced</option><option>Detailed</option></select></label><label>Coloring space<select defaultValue="Balanced"><option>Large</option><option>Balanced</option><option>Small / Intricate</option></select></label></div><div className="style-summary"><strong>Live Style Summary</strong><p>{style} illustrations · medium line weight · balanced backgrounds · designed for {audience}.</p></div></>}
 {step===4&&<><div className="wizard-title"><BookHeart/><div><h2>Set up your book format</h2><p>Choose a practical starting format for your pages.</p></div></div><div className="format-grid"><button className="format-card selected"><span className="paper portrait"></span><strong>8.5 × 11 in</strong><small>Popular print format</small></button><button className="format-card"><span className="paper portrait small"></span><strong>8 × 10 in</strong><small>Compact portrait</small></button><button className="format-card"><span className="paper square"></span><strong>8.25 × 8.25 in</strong><small>Square format</small></button><button className="format-card"><span className="paper custom"></span><strong>Custom</strong><small>Set dimensions</small></button></div><div className="form-grid top-space"><label>Orientation<select><option>Portrait</option><option>Landscape</option></select></label><label>Bleed<select><option>No bleed</option><option>Bleed</option></select></label><label>Page printing<select><option>Single-sided</option><option>Double-sided</option></select></label></div></>}
 {step===5&&<><div className="wizard-title"><Check/><div><h2>Review your new book</h2><p>Here’s the creative brief we’ll use to build your workspace.</p></div></div><div className="review-panel"><div><small>TITLE</small><strong>{title||'Untitled Coloring Book'}</strong></div><div><small>AUDIENCE</small><strong>{audience}</strong></div><div><small>PAGES</small><strong>{pages} coloring pages</strong></div><div><small>STYLE</small><strong>{style}</strong></div><div><small>FORMAT</small><strong>8.5 × 11 in · Portrait</strong></div><div><small>THEME</small><strong>{theme||'Not specified yet'}</strong></div></div><div className="ready-banner"><Sparkles/><div><strong>Your studio is ready.</strong><p>Creating the book will open its production workspace at the Book Information step.</p></div></div></>}
 <div className="wizard-actions"><button className="ghost-btn" disabled={step===1} onClick={()=>setStep(Math.max(1,step-1))}><ArrowLeft size={17}/> Back</button>{step<5?<button className="primary-btn" onClick={()=>setStep(step+1)}>Continue <ArrowRight size={17}/></button>:<button className="primary-btn">Create My Book <Sparkles size={17}/></button>}</div></div></div>
}
